// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ccm/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # proto/tx/message
type MsgProcessCrossChainTx struct {
	Submitter   string `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	FromChainId uint64 `protobuf:"varint,2,opt,name=fromChainId,proto3" json:"fromChainId,omitempty"`
	Proof       string `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	Header      string `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`
	HeaderProof string `protobuf:"bytes,5,opt,name=headerProof,proto3" json:"headerProof,omitempty"`
	CurHeader   string `protobuf:"bytes,6,opt,name=curHeader,proto3" json:"curHeader,omitempty"`
}

func (m *MsgProcessCrossChainTx) Reset()         { *m = MsgProcessCrossChainTx{} }
func (m *MsgProcessCrossChainTx) String() string { return proto.CompactTextString(m) }
func (*MsgProcessCrossChainTx) ProtoMessage()    {}
func (*MsgProcessCrossChainTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_4650de1dea793839, []int{0}
}
func (m *MsgProcessCrossChainTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProcessCrossChainTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProcessCrossChainTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProcessCrossChainTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProcessCrossChainTx.Merge(m, src)
}
func (m *MsgProcessCrossChainTx) XXX_Size() int {
	return m.Size()
}
func (m *MsgProcessCrossChainTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProcessCrossChainTx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProcessCrossChainTx proto.InternalMessageInfo

func (m *MsgProcessCrossChainTx) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgProcessCrossChainTx) GetFromChainId() uint64 {
	if m != nil {
		return m.FromChainId
	}
	return 0
}

func (m *MsgProcessCrossChainTx) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

func (m *MsgProcessCrossChainTx) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}

func (m *MsgProcessCrossChainTx) GetHeaderProof() string {
	if m != nil {
		return m.HeaderProof
	}
	return ""
}

func (m *MsgProcessCrossChainTx) GetCurHeader() string {
	if m != nil {
		return m.CurHeader
	}
	return ""
}

type MsgProcessCrossChainTxResponse struct {
}

func (m *MsgProcessCrossChainTxResponse) Reset()         { *m = MsgProcessCrossChainTxResponse{} }
func (m *MsgProcessCrossChainTxResponse) String() string { return proto.CompactTextString(m) }
func (*MsgProcessCrossChainTxResponse) ProtoMessage()    {}
func (*MsgProcessCrossChainTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4650de1dea793839, []int{1}
}
func (m *MsgProcessCrossChainTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProcessCrossChainTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProcessCrossChainTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProcessCrossChainTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProcessCrossChainTxResponse.Merge(m, src)
}
func (m *MsgProcessCrossChainTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgProcessCrossChainTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProcessCrossChainTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProcessCrossChainTxResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgProcessCrossChainTx)(nil), "Switcheo.polynetworkcosmos.ccm.MsgProcessCrossChainTx")
	proto.RegisterType((*MsgProcessCrossChainTxResponse)(nil), "Switcheo.polynetworkcosmos.ccm.MsgProcessCrossChainTxResponse")
}

func init() { proto.RegisterFile("ccm/tx.proto", fileDescriptor_4650de1dea793839) }

var fileDescriptor_4650de1dea793839 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x6b, 0xfa, 0x07, 0xd5, 0x30, 0x59, 0xa8, 0x8a, 0x10, 0xb2, 0xa2, 0x4e, 0x5d, 0x70,
	0xa4, 0x22, 0x31, 0x32, 0xd0, 0x05, 0x24, 0x2a, 0x55, 0x85, 0x89, 0xad, 0x75, 0xdd, 0x26, 0x02,
	0xe7, 0x22, 0x9f, 0xa3, 0xa6, 0x23, 0x23, 0x1b, 0x9f, 0x0a, 0x31, 0x76, 0x64, 0x44, 0xc9, 0x17,
	0x41, 0x75, 0x5a, 0xc8, 0x50, 0x31, 0xb0, 0xf9, 0x7e, 0xbe, 0x77, 0xef, 0xd9, 0x47, 0x8f, 0xa5,
	0xd4, 0x81, 0xcd, 0x44, 0x62, 0xc0, 0x02, 0xe3, 0xf7, 0xcb, 0xc8, 0xca, 0x50, 0x81, 0x48, 0xe0,
	0x79, 0x15, 0x2b, 0xbb, 0x04, 0xf3, 0x24, 0x01, 0x35, 0xa0, 0x90, 0x52, 0x77, 0xdf, 0x09, 0xed,
	0x0c, 0x71, 0x31, 0x32, 0x20, 0x15, 0xe2, 0xc0, 0x00, 0xe2, 0x20, 0x9c, 0x44, 0xf1, 0x43, 0xc6,
	0xce, 0x68, 0x1b, 0xd3, 0xa9, 0x8e, 0xac, 0x55, 0xc6, 0x23, 0x3e, 0xe9, 0xb5, 0xc7, 0xbf, 0x80,
	0xf9, 0xf4, 0x68, 0x6e, 0x40, 0xbb, 0xe6, 0xdb, 0x99, 0x77, 0xe0, 0x93, 0x5e, 0x63, 0x5c, 0x45,
	0xec, 0x84, 0x36, 0x13, 0x03, 0x30, 0xf7, 0xea, 0x4e, 0x5b, 0x16, 0xac, 0x43, 0x5b, 0xa1, 0x9a,
	0xcc, 0x94, 0xf1, 0x1a, 0x0e, 0x6f, 0xab, 0xcd, 0xbc, 0xf2, 0x34, 0x72, 0x9a, 0xa6, 0xbb, 0xac,
	0xa2, 0x4d, 0x1e, 0x99, 0x9a, 0x9b, 0x52, 0xdc, 0x2a, 0xf3, 0xfc, 0x80, 0xae, 0x4f, 0xf9, 0xfe,
	0x77, 0x8c, 0x15, 0x26, 0x10, 0xa3, 0xea, 0xbf, 0x12, 0x5a, 0x1f, 0xe2, 0x82, 0xbd, 0x10, 0x7a,
	0xb8, 0xed, 0x63, 0x97, 0xe2, 0xef, 0xff, 0x11, 0xfb, 0x67, 0x9e, 0x5e, 0xfd, 0x4f, 0xb7, 0xcb,
	0x72, 0x7d, 0xf7, 0x91, 0x73, 0xb2, 0xce, 0x39, 0xf9, 0xca, 0x39, 0x79, 0x2b, 0x78, 0x6d, 0x5d,
	0xf0, 0xda, 0x67, 0xc1, 0x6b, 0x8f, 0xfd, 0x45, 0x64, 0xc3, 0x74, 0x2a, 0x24, 0xe8, 0x60, 0xe7,
	0x11, 0x54, 0x3c, 0xce, 0x4b, 0x93, 0x20, 0x0b, 0xdc, 0x9e, 0x57, 0x89, 0xc2, 0x69, 0xcb, 0xed,
	0xfa, 0xe2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x20, 0xa5, 0xf4, 0xdf, 0xfb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	Process(ctx context.Context, in *MsgProcessCrossChainTx, opts ...grpc.CallOption) (*MsgProcessCrossChainTxResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) Process(ctx context.Context, in *MsgProcessCrossChainTx, opts ...grpc.CallOption) (*MsgProcessCrossChainTxResponse, error) {
	out := new(MsgProcessCrossChainTxResponse)
	err := c.cc.Invoke(ctx, "/Switcheo.polynetworkcosmos.ccm.Msg/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	Process(context.Context, *MsgProcessCrossChainTx) (*MsgProcessCrossChainTxResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) Process(ctx context.Context, req *MsgProcessCrossChainTx) (*MsgProcessCrossChainTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgProcessCrossChainTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Switcheo.polynetworkcosmos.ccm.Msg/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Process(ctx, req.(*MsgProcessCrossChainTx))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Switcheo.polynetworkcosmos.ccm.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Msg_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ccm/tx.proto",
}

func (m *MsgProcessCrossChainTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProcessCrossChainTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProcessCrossChainTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CurHeader) > 0 {
		i -= len(m.CurHeader)
		copy(dAtA[i:], m.CurHeader)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CurHeader)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.HeaderProof) > 0 {
		i -= len(m.HeaderProof)
		copy(dAtA[i:], m.HeaderProof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.HeaderProof)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Header) > 0 {
		i -= len(m.Header)
		copy(dAtA[i:], m.Header)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Header)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x1a
	}
	if m.FromChainId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FromChainId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgProcessCrossChainTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProcessCrossChainTxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProcessCrossChainTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgProcessCrossChainTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.FromChainId != 0 {
		n += 1 + sovTx(uint64(m.FromChainId))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Header)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.HeaderProof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CurHeader)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgProcessCrossChainTxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgProcessCrossChainTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProcessCrossChainTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProcessCrossChainTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromChainId", wireType)
			}
			m.FromChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FromChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Header = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeaderProof", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeaderProof = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurHeader", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurHeader = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgProcessCrossChainTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProcessCrossChainTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProcessCrossChainTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
