// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: btcx/denom_cross_chain_info.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DenomCrossChainInfo struct {
	DenomInfo   DenomInfo `protobuf:"bytes,1,opt,name=denom_info,json=denomInfo,proto3" json:"denom_info" yaml:"denom_info"`
	ToChainId   uint64    `protobuf:"varint,2,opt,name=to_chain_id,json=toChainId,proto3" json:"to_chain_id,omitempty" yaml:"to_chain_id"`
	ToAssetHash string    `protobuf:"bytes,3,opt,name=to_asset_hash,json=toAssetHash,proto3" json:"to_asset_hash,omitempty" yaml:"to_asset_hash"`
}

func (m *DenomCrossChainInfo) Reset()         { *m = DenomCrossChainInfo{} }
func (m *DenomCrossChainInfo) String() string { return proto.CompactTextString(m) }
func (*DenomCrossChainInfo) ProtoMessage()    {}
func (*DenomCrossChainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_25ff300fab0f746d, []int{0}
}
func (m *DenomCrossChainInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DenomCrossChainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DenomCrossChainInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DenomCrossChainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DenomCrossChainInfo.Merge(m, src)
}
func (m *DenomCrossChainInfo) XXX_Size() int {
	return m.Size()
}
func (m *DenomCrossChainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DenomCrossChainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DenomCrossChainInfo proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DenomCrossChainInfo)(nil), "Switcheo.carbon.btcx.DenomCrossChainInfo")
}

func init() { proto.RegisterFile("btcx/denom_cross_chain_info.proto", fileDescriptor_25ff300fab0f746d) }

var fileDescriptor_25ff300fab0f746d = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0x2a, 0x49, 0xae,
	0xd0, 0x4f, 0x49, 0xcd, 0xcb, 0xcf, 0x8d, 0x4f, 0x2e, 0xca, 0x2f, 0x2e, 0x8e, 0x4f, 0xce, 0x48,
	0xcc, 0xcc, 0x8b, 0xcf, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x09,
	0x2e, 0xcf, 0x2c, 0x49, 0xce, 0x48, 0xcd, 0xd7, 0x4b, 0x4e, 0x2c, 0x4a, 0xca, 0xcf, 0xd3, 0x03,
	0x69, 0x91, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x2b, 0xd0, 0x07, 0xb1, 0x20, 0x6a, 0xa5, 0x44,
	0x91, 0x8c, 0x43, 0x18, 0xa1, 0xf4, 0x86, 0x91, 0x4b, 0xd8, 0x05, 0x24, 0xe8, 0x0c, 0xb2, 0xc2,
	0x19, 0x64, 0x83, 0x67, 0x5e, 0x5a, 0xbe, 0x50, 0x24, 0x17, 0x17, 0x42, 0xad, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0xb7, 0x91, 0xbc, 0x1e, 0x36, 0xfb, 0xf4, 0xc0, 0xda, 0x41, 0x9a, 0x9c, 0x24, 0x4f,
	0xdc, 0x93, 0x67, 0xf8, 0x74, 0x4f, 0x5e, 0xb0, 0x32, 0x31, 0x37, 0xc7, 0x4a, 0x09, 0x61, 0x80,
	0x52, 0x10, 0x67, 0x0a, 0x4c, 0x95, 0x90, 0x19, 0x17, 0x77, 0x49, 0x3e, 0xcc, 0x33, 0x29, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x2c, 0x4e, 0x62, 0x9f, 0xee, 0xc9, 0x0b, 0x41, 0xb4, 0x21, 0x49, 0x2a,
	0x05, 0x71, 0x96, 0xe4, 0x43, 0x1c, 0x95, 0x22, 0x64, 0xc3, 0xc5, 0x5b, 0x92, 0x1f, 0x9f, 0x58,
	0x5c, 0x9c, 0x5a, 0x12, 0x9f, 0x91, 0x58, 0x9c, 0x21, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0xe9, 0x24,
	0xf1, 0xe9, 0x9e, 0xbc, 0x08, 0x5c, 0x27, 0x42, 0x5a, 0x29, 0x88, 0xbb, 0x24, 0xdf, 0x11, 0xc4,
	0xf5, 0x48, 0x2c, 0xce, 0xb0, 0x62, 0xe9, 0x58, 0x20, 0xcf, 0xe0, 0xe4, 0x7b, 0xe2, 0x91, 0x1c,
	0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1, 0xb1,
	0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0xc6, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9,
	0xf9, 0xb9, 0xfa, 0x30, 0x6f, 0xea, 0x17, 0xe4, 0xe7, 0x54, 0xe6, 0xa5, 0x96, 0x94, 0xe7, 0x17,
	0x65, 0xeb, 0x26, 0xe7, 0x17, 0xe7, 0xe6, 0x17, 0xeb, 0x57, 0xe8, 0x83, 0x03, 0xb2, 0xa4, 0xb2,
	0x20, 0xb5, 0x38, 0x89, 0x0d, 0x1c, 0x88, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x95,
	0xfa, 0x72, 0xac, 0x01, 0x00, 0x00,
}

func (m *DenomCrossChainInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DenomCrossChainInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DenomCrossChainInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ToAssetHash) > 0 {
		i -= len(m.ToAssetHash)
		copy(dAtA[i:], m.ToAssetHash)
		i = encodeVarintDenomCrossChainInfo(dAtA, i, uint64(len(m.ToAssetHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ToChainId != 0 {
		i = encodeVarintDenomCrossChainInfo(dAtA, i, uint64(m.ToChainId))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.DenomInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintDenomCrossChainInfo(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintDenomCrossChainInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovDenomCrossChainInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DenomCrossChainInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DenomInfo.Size()
	n += 1 + l + sovDenomCrossChainInfo(uint64(l))
	if m.ToChainId != 0 {
		n += 1 + sovDenomCrossChainInfo(uint64(m.ToChainId))
	}
	l = len(m.ToAssetHash)
	if l > 0 {
		n += 1 + l + sovDenomCrossChainInfo(uint64(l))
	}
	return n
}

func sovDenomCrossChainInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDenomCrossChainInfo(x uint64) (n int) {
	return sovDenomCrossChainInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DenomCrossChainInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDenomCrossChainInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DenomCrossChainInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DenomCrossChainInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDenomCrossChainInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDenomCrossChainInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDenomCrossChainInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DenomInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToChainId", wireType)
			}
			m.ToChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDenomCrossChainInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ToChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAssetHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDenomCrossChainInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDenomCrossChainInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDenomCrossChainInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAssetHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDenomCrossChainInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDenomCrossChainInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDenomCrossChainInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDenomCrossChainInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDenomCrossChainInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDenomCrossChainInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDenomCrossChainInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDenomCrossChainInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDenomCrossChainInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDenomCrossChainInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDenomCrossChainInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDenomCrossChainInfo = fmt.Errorf("proto: unexpected end of group")
)
