// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: headersync/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetConsensusPeersRequest struct {
	ChainId uint64 `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
}

func (m *QueryGetConsensusPeersRequest) Reset()         { *m = QueryGetConsensusPeersRequest{} }
func (m *QueryGetConsensusPeersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetConsensusPeersRequest) ProtoMessage()    {}
func (*QueryGetConsensusPeersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ce0f08461462856, []int{0}
}
func (m *QueryGetConsensusPeersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetConsensusPeersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetConsensusPeersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetConsensusPeersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetConsensusPeersRequest.Merge(m, src)
}
func (m *QueryGetConsensusPeersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetConsensusPeersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetConsensusPeersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetConsensusPeersRequest proto.InternalMessageInfo

func (m *QueryGetConsensusPeersRequest) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

type QueryGetConsensusPeersResponse struct {
	ConsensusPeers *ConsensusPeers `protobuf:"bytes,1,opt,name=consensusPeers,proto3" json:"consensusPeers,omitempty"`
}

func (m *QueryGetConsensusPeersResponse) Reset()         { *m = QueryGetConsensusPeersResponse{} }
func (m *QueryGetConsensusPeersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetConsensusPeersResponse) ProtoMessage()    {}
func (*QueryGetConsensusPeersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ce0f08461462856, []int{1}
}
func (m *QueryGetConsensusPeersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetConsensusPeersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetConsensusPeersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetConsensusPeersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetConsensusPeersResponse.Merge(m, src)
}
func (m *QueryGetConsensusPeersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetConsensusPeersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetConsensusPeersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetConsensusPeersResponse proto.InternalMessageInfo

func (m *QueryGetConsensusPeersResponse) GetConsensusPeers() *ConsensusPeers {
	if m != nil {
		return m.ConsensusPeers
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetConsensusPeersRequest)(nil), "Switcheo.polynetworkcosmos.headersync.QueryGetConsensusPeersRequest")
	proto.RegisterType((*QueryGetConsensusPeersResponse)(nil), "Switcheo.polynetworkcosmos.headersync.QueryGetConsensusPeersResponse")
}

func init() { proto.RegisterFile("headersync/query.proto", fileDescriptor_1ce0f08461462856) }

var fileDescriptor_1ce0f08461462856 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0x48, 0x4d, 0x4c,
	0x49, 0x2d, 0x2a, 0xae, 0xcc, 0x4b, 0xd6, 0x2f, 0x2c, 0x4d, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x52, 0x0d, 0x2e, 0xcf, 0x2c, 0x49, 0xce, 0x48, 0xcd, 0xd7, 0x2b, 0xc8, 0xcf,
	0xa9, 0xcc, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0x4e, 0xce, 0x2f, 0xce, 0xcd, 0x2f, 0xd6, 0x43,
	0x68, 0x91, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc,
	0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x18, 0x22, 0xa5, 0x80, 0x64, 0x78,
	0x72, 0x7e, 0x5e, 0x71, 0x6a, 0x5e, 0x71, 0x69, 0x71, 0x7c, 0x41, 0x6a, 0x6a, 0x11, 0x54, 0x85,
	0x92, 0x25, 0x97, 0x6c, 0x20, 0xc8, 0x56, 0xf7, 0xd4, 0x12, 0x67, 0x98, 0x82, 0x00, 0x90, 0x7c,
	0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x04, 0x17, 0x7b, 0x72, 0x46, 0x62, 0x66, 0x9e,
	0x67, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x8c, 0xab, 0x54, 0xcf, 0x25, 0x87, 0x4b,
	0x6b, 0x71, 0x01, 0x48, 0x40, 0x28, 0x96, 0x8b, 0x2f, 0x19, 0x45, 0x06, 0x6c, 0x04, 0xb7, 0x91,
	0xa9, 0x1e, 0x51, 0x9e, 0xd3, 0x43, 0x33, 0x16, 0xcd, 0x30, 0xa3, 0x97, 0x8c, 0x5c, 0xac, 0x60,
	0x17, 0x08, 0xdd, 0x67, 0xe4, 0x12, 0xc4, 0x70, 0x86, 0x90, 0x0b, 0x91, 0xd6, 0xe0, 0x0d, 0x00,
	0x29, 0x57, 0x0a, 0x4d, 0x81, 0x84, 0x85, 0x92, 0x6d, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0xcc, 0x85,
	0x4c, 0xf5, 0x61, 0xc6, 0xe9, 0x63, 0x18, 0xa7, 0x8f, 0x14, 0x5d, 0xa8, 0xc6, 0x38, 0x05, 0x9f,
	0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31,
	0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x65, 0x7a, 0x66, 0x49, 0x46, 0x69,
	0x92, 0x5e, 0x72, 0x7e, 0x2e, 0x56, 0xa3, 0x75, 0xa1, 0x66, 0x57, 0x20, 0x9b, 0x5e, 0x52, 0x59,
	0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x4e, 0x03, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x26,
	0x98, 0x05, 0x84, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	GetConsensusPeers(ctx context.Context, in *QueryGetConsensusPeersRequest, opts ...grpc.CallOption) (*QueryGetConsensusPeersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetConsensusPeers(ctx context.Context, in *QueryGetConsensusPeersRequest, opts ...grpc.CallOption) (*QueryGetConsensusPeersResponse, error) {
	out := new(QueryGetConsensusPeersResponse)
	err := c.cc.Invoke(ctx, "/Switcheo.polynetworkcosmos.headersync.Query/GetConsensusPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	GetConsensusPeers(context.Context, *QueryGetConsensusPeersRequest) (*QueryGetConsensusPeersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetConsensusPeers(ctx context.Context, req *QueryGetConsensusPeersRequest) (*QueryGetConsensusPeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsensusPeers not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetConsensusPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetConsensusPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetConsensusPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Switcheo.polynetworkcosmos.headersync.Query/GetConsensusPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetConsensusPeers(ctx, req.(*QueryGetConsensusPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Switcheo.polynetworkcosmos.headersync.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConsensusPeers",
			Handler:    _Query_GetConsensusPeers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "headersync/query.proto",
}

func (m *QueryGetConsensusPeersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetConsensusPeersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetConsensusPeersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ChainId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetConsensusPeersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetConsensusPeersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetConsensusPeersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConsensusPeers != nil {
		{
			size, err := m.ConsensusPeers.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetConsensusPeersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainId != 0 {
		n += 1 + sovQuery(uint64(m.ChainId))
	}
	return n
}

func (m *QueryGetConsensusPeersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConsensusPeers != nil {
		l = m.ConsensusPeers.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetConsensusPeersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetConsensusPeersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetConsensusPeersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetConsensusPeersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetConsensusPeersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetConsensusPeersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPeers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusPeers == nil {
				m.ConsensusPeers = &ConsensusPeers{}
			}
			if err := m.ConsensusPeers.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
